In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from multiprocessing import Pool
import multiprocessing

In [2]:
num_cores = multiprocessing.cpu_count()
print(f'number of cores: {num_cores}')

number of cores: 16

In [9]:
user_logs = pd.read_csv('./kaggledata/user_logs_v2.csv', index_col='msno')

In [10]:
train = pd.read_csv('./kaggledata/train.csv', index_col='msno')

In [11]:
transactions = pd.read_csv('./kaggledata/transactions.csv', index_col='msno')

In [13]:
members = pd.read_csv('./kaggledata/members_v3.csv', index_col='msno')

In [19]:
transactions

,payment_method_id,payment_plan_days,plan_list_price,actual_amount_paid,is_auto_renew,transaction_date,membership_expire_date,is_cancel
msno,,,,,,,,
YyO+tlZtAXYXoZhNr3Vg3+dfVQvrBVGO8j1mfqe4ZHc=,41,30,129,129,1,20150930,20151101,0
AZtu6Wl0gPojrEQYB8Q3vBSmE2wnZ3hi1FbK1rQQ0A4=,41,30,149,149,1,20150930,20151031,0
UkDFI97Qb6+s2LWcijVVv4rMAsORbVDT2wNXF0aVbns=,41,30,129,129,1,20150930,20160427,0
M1C56ijxozNaGD0t2h68PnH2xtx5iO5iR2MVYQB6nBI=,39,30,149,149,1,20150930,20151128,0
yvj6zyBUaqdbUQSrKsrZ+xNDVM62knauSZJzakS9OW4=,39,30,149,149,1,20150930,20151121,0
...,...,...,...,...,...,...,...,...
6AO1oJjW3YT1adWzyWhzf8hlyjeOuQatudP8FF13UB4=,38,30,149,149,0,20151030,20151129,0
wkSSJvM8E1hsNmRYE4vlOcR426v0Kd4L2E++Qxgz/bo=,36,30,150,150,0,20160331,20160530,0
VQ4KpwvezU3dqq6Bkqfjsmt4fn0JDRckkDoFFt0/UqM=,36,30,180,180,0,20161129,20161229,0
a84q/Ts47Oyyqc1N1WRasBdbgYSF/f3uqBcEAPNemoM=,41,30,99,99,1,20161130,20161231,0
oE4y2wK5E7OR8zyrCHeW02uTeI6wTwT4QTApEVBNEdM=,41,30,149,0,1,20151029,20151029,1

In [2]:
def parallelize_dataframe(df, func):
    df_split = np.array_split(df, num_cores)
    pool = Pool(num_cores)
    df = pd.concat(pool.map(func, df_split))
    pool.close()
    pool.join()
    return df

ModuleNotFoundError: No module named 'multi_process'

In [ ]:
def multiply_columns(data):
    data['length_of_word'] = data['species'].apply(lambda x: len(x))
    return data